version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  database:
    build: ./database
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database